### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by zippeurfou** [aoles/shinyURL#2]
Hi,
Here is the error:

```
Warning: Unhandled error in observer: invalid argument type
observe({
    inputValues = reactiveValuesToList(session$input, all.names = FALSE)
    inputValues = inputValues[!unlist(lapply(inputValues, function(x) inherits(x, 
        "shinyActionButtonValue")), use.names = FALSE)]
    idx = grep("_mouse_(over|out)$", names(inputValues))
    if (length(idx) > 0) 
        inputValues = inputValues[-idx]
    names = sort(names(inputValues))
    addValues = NULL
    i = 1L
    while (i <= length(names)) {
        n = names[i]
        idx = grep(sprintf("^%s[0-9]+", n), names)
        if (length(idx) == 0L) {
            i = i + 1L
        }
        else {
            value = inputValues[[n]]
            names = names[-c(i, idx)]
            if (is.null(value)) 
                value = ""
            values = as.list(value)
            names(values) = sprintf("%s[%s]", n, seq_along(value))
            addValues = c(values, addValues)
        }
    }
    inputValues = inputValues[names]
    inputValu [... truncated]
ERROR: [on_request_read] connection reset by peer
```

I am using Rmardkown

**Comment by aoles** [comment]
Hi,
thank you for reporting your problems with using shinyURL.

Can you please provide a minimal reproducible example demonstrating the issue, and the output of `sessionInfo()`?

Thanks,
Andrzej

**Comment by zippeurfou** [comment]
Thank you a lot.
Here is the App. As easy as it can get (default Rstudio shiny app):

```
---
date: "December 17, 2015"
output: html_document
runtime: shiny
---

require(shinyURL,quietly = T)
inputPanel(
  selectInput("n_breaks", label = "Number of bins:",
              choices = c(10, 20, 35, 50), selected = 20),

  sliderInput("bw_adjust", label = "Bandwidth adjustment:",
              min = 0.2, max = 2, value = 1, step = 0.2),
  shinyURL.ui()
)

renderPlot({
  hist(faithful$eruptions, probability = TRUE, breaks = as.numeric(input$n_breaks),
       xlab = "Duration (minutes)", main = "Geyser eruption duration")

  dens <- density(faithful$eruptions, adjust = input$bw_adjust)
  lines(dens, col = "blue")
})

shinyURL.server(session)
```

here is my devtool info (emulating it from the CLI):

```
> library(devtools)
> library(shinyURL)
> library(shiny)
> devtools::session_info()
Session info -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.2 (2015-08-14)
 system   x86_64, darwin13.4.0        
 ui       RStudio (0.99.486)          
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2015-12-17                  

Packages ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 package   * version  date       source                         
 bitops      1.0-6    2013-08-17 CRAN (R 3.2.0)                 
 devtools  * 1.9.1    2015-09-11 CRAN (R 3.2.0)                 
 digest      0.6.8    2014-12-31 CRAN (R 3.2.0)                 
 htmltools   0.2.6    2014-09-08 CRAN (R 3.2.0)                 
 httpuv      1.3.3    2015-08-04 CRAN (R 3.2.0)                 
 memoise     0.2.1    2014-04-22 CRAN (R 3.2.0)                 
 mime        0.4      2015-09-03 CRAN (R 3.2.0)                 
 R6          2.1.1    2015-08-19 CRAN (R 3.2.0)                 
 Rcpp        0.12.2   2015-11-15 CRAN (R 3.2.2)                 
 RCurl       1.95-4.7 2015-06-30 CRAN (R 3.2.0)                 
 shiny     * 0.12.2   2015-08-05 CRAN (R 3.2.0)                 
 shinyURL  * 0.0.19   2015-12-17 Github (aoles/shinyURL@9edb7e3)
 xtable      1.8-0    2015-11-02 CRAN (R 3.2.0)     

```

And the error:

```
processing file: testApp.Rmd
  |.............                                                    |  20%
  ordinary text without R code

  |..........................                                       |  40%
label: unnamed-chunk-1
  |.......................................                          |  60%
  ordinary text without R code

  |....................................................             |  80%
label: unnamed-chunk-2 (with options) 
List of 1
 $ echo: logi FALSE

  |.................................................................| 100%
  ordinary text without R code


output file: /private/var/folders/6f/byx9_ytd6694gl1m20qvxtjw0000gn/T/RtmpZKVhLB/testApp.knit.md

/usr/local/bin/pandoc +RTS -K512m -RTS /private/var/folders/6f/byx9_ytd6694gl1m20qvxtjw0000gn/T/RtmpZKVhLB/testApp.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output /private/var/folders/6f/byx9_ytd6694gl1m20qvxtjw0000gn/T/RtmpZKVhLB/filed32841d370fc.html --smart --email-obfuscation none --standalone --section-divs --template /Library/Frameworks/R.framework/Versions/3.2/Resources/library/rmarkdown/rmd/h/default.html --variable 'theme:bootstrap' --mathjax --variable 'mathjax-url:https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --no-highlight --variable highlightjs=filed32841d370fc_files/highlight 

Output created: /private/var/folders/6f/byx9_ytd6694gl1m20qvxtjw0000gn/T/RtmpZKVhLB/filed32841d370fc.html
Warning: Unhandled error in observer: invalid argument type
observe({
    inputValues = reactiveValuesToList(session$input, all.names = FALSE)
    inputValues = inputValues[!unlist(lapply(inputValues, function(x) inherits(x, 
        "shinyActionButtonValue")), use.names = FALSE)]
    idx = grep("_mouse_(over|out)$", names(inputValues))
    if (length(idx) > 0) 
        inputValues = inputValues[-idx]
    names = sort(names(inputValues))
    addValues = NULL
    i = 1L
    while (i <= length(names)) {
        n = names[i]
        idx = grep(sprintf("^%s[0-9]+", n), names)
        if (length(idx) == 0L) {
            i = i + 1L
        }
        else {
            value = inputValues[[n]]
            names = names[-c(i, idx)]
            if (is.null(value)) 
                value = ""
            values = as.list(value)
            names(values) = sprintf("%s[%s]", n, seq_along(value))
            addValues = c(values, addValues)
        }
    }
    inputValues = inputValues[names]
    inputValu [... truncated]
ERROR: [on_request_read] connection reset by peer
```

**Comment by aoles** [comment]
Many thanks for all the details! 

A workaround for this issue is to provide an explicit app's declaration in a call to `shinyApp`, as in the following example.

``````
---
title: "Embedded Shiny Application"
output: html_document
runtime: shiny
---

```{r, echo=FALSE}
library(shinyURL)
shinyApp(
  ui = fluidPage(
    fluidRow(
      column(6, sliderInput("bins", "Number of bins:", min=1,  max=50, value=30, width="100%")),
      column(6, shinyURL.ui()),
      plotOutput("plot")
    )
  ),
  server = function(input, output, session) {
    shinyURL.server(session)
    output$plot <- renderPlot({
      x <- faithful[, 2]
      bins <- seq(min(x), max(x), length.out = input$bins + 1)
      hist(x, breaks = bins, col = 'darkgray', border = 'white')
    })
  },
  options = list(height = 520)
)
```
``````

Please let me know whether this works for you.

**Comment by zippeurfou** [comment]
It does works.
However, for my use case it is not good. I have multiple ui element that are in multiple chunk that make this design not possible.
Any chance you might consider adapting it for Rmd?

**Comment by zippeurfou** [comment]
@aoles any chance you might "fix" it?

**Comment by aoles** [comment]
If it's technically feasible I would definitely like to enable shinyURL for Rmd documents. The thing is, for the moment I'm not quite sure how hard it would be and what the actual problem is. I already tried contacting the shiny authors regarding this issue https://github.com/rstudio/shiny/issues/1040 but didn't get any answer yet. I will certainly investigate this further and keep you updated.

**Comment by aoles** [comment]
Hi @zippeurfou,
I've just commited a fix for using shinyURL with interactive rmarkdown documents. You're welcome to give it a try!

**Comment by zippeurfou** [comment]
@aoles I am right now.
You made my day!
So far I see only one thing not working:

```
selectInput("transformData", label = "Transform:",
              choices =c("None"="none","Normalize stats"="normalize"),selected = "none", multiple=TRUE, selectize=TRUE)
```

If I select more than one it won't work.
Any idea why?

**Comment by aoles** [comment]
Hi @zippeurfou,
many thanks for reporting the issue with `selectInput` when the selection of multiple items is allowed. The problem was due to some changes introduced in shiny 0.12.0. I've fixed this in https://github.com/aoles/shinyURL/commit/77ca91ab2d05c980104709debfc6336eae2ca4c8 along with another patch for numeric inputs.

**Comment by zippeurfou** [comment]
@aoles Everything works great now.
It still does not work for all cases (i.e. try with this example: https://gallery.shinyapps.io/106-plot-interaction-exclude/). However, I believe it must be in the logic itself and not your module.
